### ISSUE TITLE
Grid Column a yeni bir DELETE button eklenmesi 

### ISSUE THREAD

**Issue by yakintech** [yakintech/chat-app-site#3]
![image](https://user-images.githubusercontent.com/16878108/217536158-091f7a06-76bc-4dc4-8e20-367262f59ca5.png)

**Comment by RuslanMehdiyev** [comment]
const columns = [
    { field: "id", headerName: "Group ID", width: 150 },
    { field: "name", headerName: "Name", width: 150 },
    {
      field: "createDate",
      headerName: "Create Date",
      width: 150,
    },
    { field: "members", headerName: "Members", width: "400" },
    {
      field: "actions",
      headerName: "Actions",
      width: 150,
      renderCell: (params) => {
        return <button onClick={() => handleDelete(params.id)}>Delete</button>;
      },
    },
  ];

  const handleDelete = (id) => {
    console.log(id);
  };

Change columns array to this code to get delete button for each row, and add handleDelete function to get data.id for manipulating over the data
